name: Build installers

on:
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    name: Build installer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: linux-amd64
          - os: macos-latest
            asset_name: macos-amd64
          - os: windows-latest
            asset_name: windows-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Build installer
        run: mvn package -DskipTests=true

      - name: Upload installers to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          promote: true
          file_glob: true
          file: target/${{ github.event.repository.name }}_${{ github.ref_name }}.*
          tag: ${{ github.ref }}