name: Build installers

on:
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    name: Build installer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #          - os: ubuntu-latest
          #            asset_name: linux-amd64
          #            executable-suffix: .rpm
          - os: ubuntu-latest
            asset_name: linux-amd64
            executable-suffix: .deb
          - os: macos-latest
            asset_name: macos-amd64
            executable-suffix: .dmg
          - os: windows-latest
            asset_name: windows-amd64
            executable-suffix: .msi
    #          - os: windows-latest
    #            asset_name: windows-amd64
    #            executable-suffix: .exe

    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Build installer
        run: mvn package -DskipTests=true

      - name: Upload installer to job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.asset_name }}${{ matrix.executable-suffix }}
          path: target/${{ github.event.repository.name }}_${{ github.ref_name }}${{ matrix.executable-suffix }}

      - name: Upload installer to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ github.event.repository.name }}_${{ github.ref_name }}${{ matrix.executable-suffix }}
          asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.asset_name }}${{ matrix.executable-suffix }}
          tag: ${{ github.ref }}